spring:
  application:
    name: QR Storage
  data:
    mongodb:
      uri: ""
      database: ""
      username: ""
      password: ""
  security:
    token:
      jwt-expiration-seconds: 60000
      jwt-secret: 18289470367876376813706236566407
debug: false